#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// 获取当前目录
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 获取项目根目录 (webview 的父目录)
const projectRoot = path.resolve(__dirname, '../..');
const buildGradlePath = path.join(projectRoot, 'build.gradle');

// 读取 build.gradle 文件
const buildGradleContent = fs.readFileSync(buildGradlePath, 'utf8');

// 提取版本号
// 查找类似 version = '0.1.0-beta3' 这样的行
let versionMatch = buildGradleContent.match(/^version\s*=\s*'(.+)'$/m);
if (!versionMatch) {
  // 如果上面的正则失败，尝试另一种方式
  const lines = buildGradleContent.split('\n');
  const versionLine = lines.find(line => line.trim().startsWith('version ='));
  if (versionLine) {
    const match = versionLine.match(/version\s*=\s*'(.+)'/);
    if (match) {
      versionMatch = match;
    }
  }
}
if (!versionMatch) {
  console.error('Error: Could not find version in build.gradle');
  process.exit(1);
}

const version = versionMatch[1];
console.log(`Found version: ${version}`);

// 创建版本文件供 webview 使用
const versionDir = path.join(__dirname, '../src/version');
if (!fs.existsSync(versionDir)) {
  fs.mkdirSync(versionDir, { recursive: true });
}

const versionFilePath = path.join(versionDir, 'version.ts');
const versionFileContent = `// Auto-generated version file
// This file is automatically generated during the build process
// Do not edit manually

export const APP_VERSION = '${version}';
`;

fs.writeFileSync(versionFilePath, versionFileContent);
console.log(`Version file created at: ${versionFilePath}`);
