idea.auto.reload.plugins=false
idea.filewatcher.disabled=true
idea.is.internal=true
idea.plugin.in.sandbox.mode=true
idea.plugins.load.timeout=60000
performance.watcher.unresponsive.interval.ms=60000

